### ISSUE TITLE
Lien mort émulateur

### ISSUE THREAD

**Issue by gwentey** [BlablalandFun/blablaland-open#24]
Bonjour,

J'ai installé et lancé le serveur via npm, tout fonctionne normalement. En revanche du coté émulateur impossible de le télécharger car le lien est mort ?

Une actualisation est possible ?

Merci

**Comment by Yovach** [comment]
> Bonjour,
> 
> J'ai installé et lancé le serveur via npm, tout fonctionne normalement. En revanche du coté émulateur impossible de le télécharger car le lien est mort ?
> 
> Une actualisation est possible ?
> 
> Merci

Bonjour,
Merci du signalement !

J'ai mis à jour les liens du README.md
