### ISSUE TITLE
html

### ISSUE THREAD

**Issue by WeLegion** [BlablalandFun/blablaland-open#26]
Quand je fais partir ton code il manque toute la partie façade du site, le html, genre la console, les bbl, la boutiques etc etc, est-ce possible d'avoir accès à ces données aussi ? $$$

![image](https://user-images.githubusercontent.com/118482870/202613126-8f3b5718-5f0e-4551-9261-468a267692cf.png)

![image](https://user-images.githubusercontent.com/118482870/202613205-d4a48690-c661-443f-a45b-96ce13e0a52d.png)

**Comment by Yovach** [comment]
Bonjour, le projet n'est plus maintenu!
